// Bongo cat — the first VECTOR species. Instead of ASCII line art, each
// frame replays a table of px/rect/line ops authored in petlab
// (era-maker/tools/petlab/candidates/char-bongo-*.mjs) on a 128x64 1-bit
// panel grid. Tables live in bongo_art.h, GENERATED by
// tools/gen-bongo-art.mjs — never edit them by hand, re-run the script.
//
// Rendering model: ops are 1-bit — on:true inks in the body colour
// (white), on:false carves by painting background. Op order within a
// frame matters (carves overwrite earlier ink) and is replayed verbatim.
// Every art pixel becomes a K x K block in 1x buddy coordinates, drawn
// through buddyFillRect, which applies the shared peek/home scale and
// render-target indirection. Lines are stepped with Bresenham in art
// space so their thickness scales like everything else.

#include "../buddy.h"
#include "../buddy_common.h"
#include "bongo_art.h"

namespace bongo {

// Art-space → 1x buddy-space transform. K doubles the 32x30 art footprint
// to 64x60 at 1x, so at home scale (3x) the cat's desk spans 192px —
// comparable bulk to the 216px-wide ASCII species.
static const int K = 2;
static const int ART_CX = (BONGO_ART_MIN_X + BONGO_ART_MAX_X + 1) / 2; // 64
static const int Y_BOTTOM_1X = 70; // ASCII pets end at y=70 in 1x space
static const int Y_OFF = Y_BOTTOM_1X - K * (BONGO_ART_MAX_Y + 1);

// Landscape clock renders at 1x into an x<115 pet box while the clock
// digits start at x125 and repaint at only 1Hz — centred at
// BUDDY_X_CENTER (120) our 68px-wide self-clear box would wipe them ~80%
// of the time (verified statically: clear x86..154 vs digits x125..215).
// Recentre at 57 there: footprint becomes x23..91, safely inside the box.
static int _cx = BUDDY_X_CENTER;
static const int CLOCK_CX = 57;

static inline int ax(int x) { return _cx + K * (x - ART_CX); }
static inline int ay(int y) { return K * y + Y_OFF; }

static void drawOp(const BongoOp& o) {
  uint16_t c = (o.kind & 0x80) ? BUDDY_WHITE : BUDDY_BG;
  switch (o.kind & 0x7F) {
    case 0:  // px
      buddyFillRect(ax(o.a), ay(o.b), K, K, c);
      break;
    case 1:  // rect
      buddyFillRect(ax(o.a), ay(o.b), K * o.c, K * o.d, c);
      break;
    case 2: {  // line — Bresenham in art space, one KxK block per step
      int x0 = o.a, y0 = o.b, x1 = o.c, y1 = o.d;
      int dx = x1 > x0 ? x1 - x0 : x0 - x1, sx = x0 < x1 ? 1 : -1;
      int dy = y1 > y0 ? y0 - y1 : y1 - y0, sy = y0 < y1 ? 1 : -1;
      int err = dx + dy;
      for (;;) {
        buddyFillRect(ax(x0), ay(y0), K, K, c);
        if (x0 == x1 && y0 == y1) break;
        int e2 = 2 * err;
        if (e2 >= dy) { err += dy; x0 += sx; }
        if (e2 <= dx) { err += dx; y0 += sy; }
      }
      break;
    }
  }
}

static void drawMood(uint8_t mood, uint32_t t) {
  const BongoMood& m = BONGO_MOODS[mood];
  _cx = buddyRenderTargetIsExternal() ? CLOCK_CX : BUDDY_X_CENTER;
  // buddyTick pre-clears the whole strip, but buddyRenderTo (landscape
  // clock) only clears x<115 while the cat spans past it — so always
  // clear our own footprint (+2px margin) before replaying the frame.
  buddyFillRect(ax(BONGO_ART_MIN_X) - 2, ay(BONGO_ART_MIN_Y) - 2,
                K * (BONGO_ART_MAX_X - BONGO_ART_MIN_X + 1) + 4,
                K * (BONGO_ART_MAX_Y - BONGO_ART_MIN_Y + 1) + 4, BUDDY_BG);
  uint32_t f = (t / m.ticksPerFrame) % m.nFrames;
  for (uint16_t i = m.idx[f]; i < m.idx[f + 1]; i++) drawOp(m.ops[i]);
}

static void doSleep(uint32_t t)     { drawMood(0, t); }
static void doIdle(uint32_t t)      { drawMood(1, t); }
static void doBusy(uint32_t t)      { drawMood(2, t); }
static void doAttention(uint32_t t) { drawMood(3, t); }
static void doCelebrate(uint32_t t) { drawMood(4, t); }
static void doDizzy(uint32_t t)     { drawMood(5, t); }
static void doHeart(uint32_t t)     { drawMood(6, t); }

}  // namespace bongo

extern const Species BONGO_SPECIES = {
  "bongo",
  0xFFFF,  // white — bongo cat's body colour
  { bongo::doSleep, bongo::doIdle, bongo::doBusy, bongo::doAttention,
    bongo::doCelebrate, bongo::doDizzy, bongo::doHeart }
};
